name: Deploy to s3
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build files
    runs-on: ubuntu-latest
    steps: 
      - name: Setup node
        uses: actions/setup-node@v1
        with: 
            node-version: '16.x'
      - uses: actions/checkout@main
      - name: Build program project files
        run: |
          npm install
          npm run build
      - name: Deploy to s3
        env: 
            AWS_DEFAULT_REGION: us-east-1
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:
          aws s3 cp dist s3://philagov-vue-apps/the-latest-archive/production/ --recursive
